package com.mcs.applemusicchallenge.pokos

data class ResultPOKO(val wrapperType: String,
                      val kind: String,
                      val artistId: Long /*long*/,
                      val collectionId: Long /*long*/,
                      val trackId: Long /*long*/,
                      val artistName: String,
                      val collectionName: String,
                      val trackName: String,
                      val collectionCensoredName: String,
                      val trackCensoredName: String,
                      val collectionArtistId: Long /*long*/,
                      val collectionArtistName: String,
                      val collectionArtistViewUrl: String,
                      val artistViewUrl: String,
                      val collectionViewUrl: String,
                      val trackViewUrl: String,
                      val previewUrl: String,
                      val artworkUrl30: String,
                      val artworkUrl60: String,
                      val artworkUrl100: String,
                      val collectionPrice: Double /*float*/,
                      val trackPrice: Double /*float*/,
                      val releaseDate: String,
                      val collectionExplicitness: String,
                      val trackExplicitness: String,
                      val discCount: Int /*int*/,
                      val discNumber: Int /*int*/,
                      val trackCount: Int /*int*/,
                      val trackNumber: Int /*int*/,
                      val trackTimeMillis: Long /*long*/,
                      val country: String,
                      val currency: String,
                      val primaryGenreName: String,
                      val isStreamable: Boolean)